// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABGr49f4WFQmZkT9E17r866vdgIsv2tMI',
    appId: '1:1049368540163:web:1e86dfeb0ed205f419ca36',
    messagingSenderId: '1049368540163',
    projectId: 'sigej-66b24',
    authDomain: 'sigej-66b24.firebaseapp.com',
    storageBucket: 'sigej-66b24.firebasestorage.app',
    measurementId: 'G-L6Q3GJ9W0G',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABGr49f4WFQmZkT9E17r866vdgIsv2tMI',
    appId: '1:1049368540163:web:4dae881f31b8d0c419ca36',
    messagingSenderId: '1049368540163',
    projectId: 'sigej-66b24',
    authDomain: 'sigej-66b24.firebaseapp.com',
    storageBucket: 'sigej-66b24.firebasestorage.app',
    measurementId: 'G-1KQLLV43ZL',
  );
}
